name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    services:
      fuseki:
        image: stain/jena-fuseki
        ports:
          - 3030:3030
        env:
          FUSEKI_DATASET_1: /ontogen-test-dataset
        options: --name fuseki
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        include:
          - pair:
              elixir: 1.16.2
              otp: 24.3
            build-flags: --warnings-as-errors
          - pair:
              elixir: 1.16.2
              otp: 25.3
            build-flags: --warnings-as-errors
          - pair:
              elixir: 1.16.2
              otp: 26.2
            build-flags: --warnings-as-errors
          - pair:
              elixir: 1.17.2
              otp: 27.0
            build-flags: --warnings-as-errors
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create and copy shiro.ini
        run: |
          echo "
          ## Minimal configuration without auth from https://jena.apache.org/documentation/fuseki2/fuseki-security.html
          [main]
          localhost=org.apache.jena.fuseki.authz.LocalhostFilter

          [urls]
          ## Control functions open to anyone
          /$/server = anon
          /$/ping   = anon
          ## and the rest are restricted to localhost.
          ## See above for 'localhost'
          /$/** = localhost
          /**=anon
          " > shiro.ini
          docker cp shiro.ini fuseki:/fuseki/shiro.ini
          docker exec fuseki chown root:root /fuseki/shiro.ini
          docker exec fuseki chmod 644 /fuseki/shiro.ini

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ matrix.pair.elixir }}
          otp-version: ${{ matrix.pair.otp }}
          build-flags: --all-warnings ${{ matrix.build-flags }}

      - name: Wait for Fuseki to be ready
        run: |
          timeout 60s bash -c 'until curl -s -f -o /dev/null http://localhost:3030/; do echo "Waiting for Fuseki..."; sleep 5; done'

      - name: Run Tests
        run: mix coveralls.github ${{ matrix.build-flags }}
        if: always()
